const GENERIC_LABELS: Record<string, string> = {
  Dashboard: 'Painel',
  Settings: 'Configurações',
  Configure: 'Configurar',
  Active: 'Ativo',
  Inactive: 'Inativo',
  Pending: 'Pendente',
  Retry: 'Reprocessar',
  Cancel: 'Cancelar',
  Save: 'Salvar',
  Edit: 'Editar',
  Delete: 'Excluir',
  Create: 'Criar',
  New: 'Novo',
  Search: 'Buscar',
  Filter: 'Filtrar',
  Clear: 'Limpar',
  Details: 'Detalhes',
  'View details': 'Ver detalhes',
  Actions: 'Ações',
  Type: 'Tipo',
  Name: 'Nome',
  Code: 'Código',
  Description: 'Descrição',
  Date: 'Data',
  'Updated at': 'Atualizado em',
  'Created at': 'Criado em',
  'Last update': 'Última atualização',
  'No records found': 'Nenhum registro encontrado',
  Loading: 'Carregando',
  Error: 'Erro',
  Success: 'Sucesso',
  Warning: 'Alerta',
  Failed: 'Falhou',
  Blocked: 'Bloqueado',
  Export: 'Exportar',
  Download: 'Baixar',
  Queue: 'Fila',
  Status: 'Status',
  'All statuses': 'Todos os status',
  'All types': 'Todos os tipos',
  'Search by code or name': 'Buscar por código ou nome',
  'Fuel Journey': 'Jornada do Comboio',
  'Fuel Journeys': 'Jornadas do Comboio',
  'Fuelings': 'Abastecimentos',
  'Fueling': 'Abastecimento',
  Operator: 'Operador',
  Driver: 'Motorista',
  Equipment: 'Equipamento',
  Fleet: 'Frota',
  Implement: 'Implemento',
  Operation: 'Operação',
  'Work Order': 'Ordem de Serviço',
  'Cost Center': 'Centro de Custo',
  Hourmeter: 'Horímetro',
  'Current hourmeter': 'Horímetro atual',
  'Initial hourmeter': 'Horímetro inicial',
  'Final hourmeter': 'Horímetro final',
  'Total hourmeter': 'Horímetro total',
  Stop: 'Parada',
  'Stop reason': 'Motivo de parada',
  Timeline: 'Linha do Tempo',
  Trail: 'Rastro',
  Map: 'Mapa',
  Homologation: 'Homologação',
  Production: 'Produção',
  Integration: 'Integração',
  Integrations: 'Integrações',
  Mapping: 'Mapeamento',
  Mappings: 'Mapeamentos',
  Validation: 'Validação',
  'Pre-validation': 'Pré-validação',
  'Validation results': 'Resultados da validação',
  Dispatch: 'Envio',
  Dispatches: 'Envios',
  'Test connection': 'Testar conexão',
  'Connection test': 'Teste de conexão',
  Jobs: 'Jobs',
  Logs: 'Logs',
  'API Settings': 'Configurações da API',
  Credentials: 'Credenciais',
};

const INTEGRATION_LABELS: Record<string, string> = {
  TOTVS: 'TOTVS',
  PIMS: 'PIMS',
  'TOTVS Mapping': 'Mapeamento TOTVS',
  'TOTVS Dispatch': 'Envio TOTVS',
  'TOTVS Jobs': 'Jobs TOTVS',
  'TOTVS Logs': 'Logs TOTVS',
  'Active mappings': 'Mapeamentos ativos',
  'Validations with warning': 'Validações com alerta',
  'New mapping': 'Novo mapeamento',
  'SILO Code': 'Código SILO',
  'TOTVS Code': 'Código TOTVS',
  'SILO Name': 'Nome SILO',
  'TOTVS Name': 'Nome TOTVS',
  'All types': 'Todos os tipos',
  'All statuses': 'Todos os status',
  'Search by code or name': 'Buscar por código ou nome',
  'Send to TOTVS Homologation': 'Enviar para TOTVS Homologação',
  'PIMS Mapping': 'Mapeamento PIMS',
  'PIMS Dispatch': 'Envio PIMS',
  'PIMS Jobs': 'Jobs PIMS',
  'PIMS Logs': 'Logs PIMS',
  'Send to PIMS Homologation': 'Enviar para PIMS Homologação',
};

const FUEL_LABELS: Record<string, string> = {
  Fuel: 'Combustível',
  Fueling: 'Abastecimento',
  Fuelings: 'Abastecimentos',
  'Fuel Journey': 'Jornada do Comboio',
  'Fuel Journeys': 'Jornadas do Comboio',
  'Fuel Truck': 'Comboio',
  Pump: 'Bomba',
  Product: 'Produto',
  Diesel: 'Diesel',
  Liters: 'Litros',
  Tank: 'Tanque',
  'Initial tank': 'Tanque inicial',
  'Final tank': 'Tanque final',
  'Loaded total': 'Total carregado',
  'Supplied total': 'Total abastecido',
  'Final balance': 'Saldo final',
  'Theoretical balance': 'Saldo teórico',
  Difference: 'Diferença',
  'Automatic calculation': 'Cálculo automático',
  'Manual calculation': 'Cálculo manual',
};

const OPERATIONAL_LABELS: Record<string, string> = {
  Journey: 'Jornada',
  'Journey Start': 'Início da Jornada',
  'Journey End': 'Fim da Jornada',
  Operator: 'Operador',
  Driver: 'Motorista',
  Equipment: 'Equipamento',
  Fleet: 'Frota',
  Implement: 'Implemento',
  Operation: 'Operação',
  'Work Order': 'Ordem de Serviço',
  'Cost Center': 'Centro de Custo',
  Hourmeter: 'Horímetro',
  'Current hourmeter': 'Horímetro atual',
  'Initial hourmeter': 'Horímetro inicial',
  'Final hourmeter': 'Horímetro final',
  'Total hourmeter': 'Horímetro total',
  Stop: 'Parada',
  'Stop reason': 'Motivo de parada',
  Timeline: 'Linha do Tempo',
  Trail: 'Rastro',
  Map: 'Mapa',
};

export function translateUiLabel(value: string): string {
  return GENERIC_LABELS[value] ?? value;
}

export function translateIntegrationLabel(value: string): string {
  return INTEGRATION_LABELS[value] ?? translateUiLabel(value);
}

export function translateFuelLabel(value: string): string {
  return FUEL_LABELS[value] ?? translateUiLabel(value);
}

export function translateOperationalLabel(value: string): string {
  return OPERATIONAL_LABELS[value] ?? translateUiLabel(value);
}

